server:
  port: 9001
  servlet:
    session:
      cookie:
        name: authorization-server-session-id
        secure: false

spring:
  security:
    username: "sneakydog@yeah.net"
    password: "sneakydogTestPasswod12"
  captcha:
    enabled: false
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    check-template-location: true
  application:
    domain: http://localhost:9001
    name: sneakydog-spring-authorization-server-demo
  mvc:
    log-request-details: false



management:
  endpoints:
    web:
      exposure:
        include: "*"
