server:
  port: 9000
  servlet:
    session:
      cookie:
        name: authorization-server-session-id
        http-only: true
        secure: true

  error:
    include-exception: on
    include-binding-errors: on_param
    include-message: on_param
    include-stacktrace: on_param

spring:
  security:
    enable2fa: true
  profiles:
    active: local
  application:
    name: sneakydog-spring-authorization-server-demo
  jackson:
    generator:
      write-numbers-as-strings: true
  quartz:
    job-store-type: jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.3.235:3306/local2"
    username: root
    password: 123456
  #  redis:
#    redisson:
#      config: |
#        singleServerConfig:
#          idleConnectionTimeout: 10000
#          connectTimeout: 10000
#          timeout: 3000
#          retryAttempts: 3
#          retryInterval: 1500
#          subscriptionsPerConnection: 5
#          clientName: test
#          address: "redis://192.168.3.48:6379"
#          password: "HomeRedisPwd.@123456"
#          subscriptionConnectionMinimumIdleSize: 1
#          subscriptionConnectionPoolSize: 50
#          connectionMinimumIdleSize: 32
#          connectionPoolSize: 64
#          database: 0
#          dnsMonitoringInterval: 5000
#        threads: 0
#        nettyThreads: 0
#        codec: !<org.redisson.codec.JsonJacksonCodec> {}
#        "transportMode": "NIO"
  mail:
    default-encoding: utf-8
    username: 517233020@qq.com
    password: cpwikrsuennjbhfh
    host: "smtp.qq.com"
    port: "587"
    protocol: smtp
    test-connection: false
    properties:
        "mail.smtp.auth": "true"
        "mail.smtp.SocketFactory": "javax.net.ssl.SSLSocketFactory"
        "mail.debug": "false"
        "mail.smtp.starttls.enable": "true"
        "mail.smtp.starttls.required": "true"
  data:
    redis:
      repositories:
        enabled: false
      host: 192.168.3.235
      port: 6379
      password: 123456
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    check-template-location: true
  mvc:
    log-request-details: false


logging:
  level:
    "org.springframework.security": debug
    "org.springframework.jdbc.core": trace



